kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.Service_name}}
spec:
  selector:
    app: music
  #type: {{ .Values.service.selector_type}}
  {{ if .Values.Ingress.enabled  }}
    type: ClusterIP
  {{ else }}
    type: LoadBalancer
  {{ end }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.targetPort}}
